# Python Numpy Tutorial #1

## Numpy

In [46]:
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

## list 형태의 배열

In [3]:
a = [1, 2, 3]

In [4]:
print(a)

[1, 2, 3]


## Numpy 사용한 배열

In [5]:
a = np.array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
a.shape

(3,)

In [9]:
Z = np.arange(9)
print(Z)

[0 1 2 3 4 5 6 7 8]


In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [12]:
Z = np.arange(10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


## Axis

In [14]:
a = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


In [15]:
np.mean(a)

2.5

<Axis ↓ 向>

In [16]:
np.mean(a, axis=0)

array([2., 3.])

In [17]:
np.sum(a, axis=0)

array([4, 6])

<Axis → 向>

In [18]:
np.mean(a, axis=1)

array([1.5, 3.5])

In [19]:
np.sum(a, axis=1)

array([3, 7])

## Sliciing and dicing 

In [20]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a[2:7:2]

array([2, 4, 6])

In [22]:
a[:4]

array([0, 1, 2, 3])

In [23]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [24]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [25]:
a.shape

(3, 3)

In [27]:
a[..., 1]

array([2, 4, 5])

In [28]:
a[1,...]

array([3, 4, 5])

In [29]:
a[...,1:]

array([[2, 3],
       [4, 5],
       [5, 6]])

In [30]:
a[1:3,...]

array([[3, 4, 5],
       [4, 5, 6]])

In [31]:
a[1:3,[0,2]]

array([[3, 5],
       [4, 6]])

In [32]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

## Broadcast 

In [34]:
A = np.array([[56.0, 0.0, 4.0, 68.0, ],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.   68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [35]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.   76.9]


In [36]:
percentage = 100 *A / cal
print(percentage)

[[94.91525424  0.          2.58064516 88.42652796]
 [ 2.03389831 43.51464435 33.5483871  10.40312094]
 [ 3.05084746 56.48535565 63.87096774  1.17035111]]


## Stack

In [37]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

세로 쌓기

In [38]:
c = np.vstack((a,b))
print(c)
print(c.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


가로 쌓기

In [39]:
d = np.hstack((a,b))
print(d)

[1 2 3 4 5 6 7 8]


## 형변환

In [40]:
x = np.array([-2.0, 1.2, 3.7])
y = x > 0
print(y)

[False  True  True]


In [41]:
y = y.astype(np.int)
print(y)

[0 1 1]


## Noise 

In [42]:
x = np.arange(0, 6, 0.1)
y = np.sin(x)

In [43]:
y

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666])

In [44]:
signal_length = y.shape[0]
print(signal_length)

60


In [45]:
noise = np.random.normal(0, 1, signal_length)
y2 = y + 0.2* noise

In [47]:
plt.plot(x, y)
plt.plot(x, y2)

NameError: name 'plt' is not defined

## 배열 형태 변환 

In [48]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [50]:
A = np.random.rand(4, 3, 2)
print(A)

[[[0.74795076 0.35716261]
  [0.48107653 0.29956577]
  [0.33725643 0.99664806]]

 [[0.80796823 0.27589307]
  [0.19644317 0.48128483]
  [0.63549141 0.57103386]]

 [[0.06747505 0.09352849]
  [0.71815037 0.90318737]
  [0.88292785 0.75421886]]

 [[0.02543476 0.02689876]
  [0.23218846 0.83987313]
  [0.37954314 0.4298401 ]]]


In [51]:
A = A.reshape(12, 2)
print(A)

[[0.74795076 0.35716261]
 [0.48107653 0.29956577]
 [0.33725643 0.99664806]
 [0.80796823 0.27589307]
 [0.19644317 0.48128483]
 [0.63549141 0.57103386]
 [0.06747505 0.09352849]
 [0.71815037 0.90318737]
 [0.88292785 0.75421886]
 [0.02543476 0.02689876]
 [0.23218846 0.83987313]
 [0.37954314 0.4298401 ]]


## Random 

np.random.choice

In [52]:
np.random.seed(0)
p = np.array([0.1, 0.0, 0.7, 0.2])

In [53]:
for i in range(10):
    index = np.random.choice([0, 1, 2, 3], p = p.ravel())
    print(i, index)

0 2
1 2
2 2
3 2
4 2
5 2
6 2
7 3
8 3
9 2


In [54]:
v = [0,0,0,0]
ntest = 1000
for i in range(ntest):
    idx = np.random.choice([0,1,2,3], p = p.ravel())
    v[idx] += 1

np.random.permutation

In [55]:
m1 = np.random.permutation(5)
print(m1)

[2 1 4 0 3]


In [56]:
X = np.array([10, 20, 30, 40, 50])
shuffled_X = X[m1]

In [57]:
print(X)
print(shuffled_X)

[10 20 30 40 50]
[30 20 50 10 40]


In [58]:
x1 = [2, 4, 8, 10, 20]
x2 = [0.2, 0.4, -0.8, 1.0, -2.0]
X = np.transpose(np.vstack((x1, x2)))

In [59]:
print(X)
print(X.shape)

[[ 2.   0.2]
 [ 4.   0.4]
 [ 8.  -0.8]
 [10.   1. ]
 [20.  -2. ]]
(5, 2)


In [60]:
permutation = np.random.permutation(5)

In [61]:
X_shuffle = X[permutation]

In [62]:
print(X_shuffle)

[[ 8.  -0.8]
 [10.   1. ]
 [20.  -2. ]
 [ 4.   0.4]
 [ 2.   0.2]]
